yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main_page'),
    path('group/<slug>/', views.group_posts, name='group_posts_list'),
] 

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.TextField()
    slug = models.TextField()
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    ) 


# Create your models here.

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post, Group

# Главная страница
def index(request):
    # Одна строка вместо тысячи слов на SQL:
    # в переменную posts будет сохранена выборка из 10 объектов модели Post,
    # отсортированных по полю pub_date по убыванию (от больших значений к меньшим)
    title = 'Последние обновления на сайте'
    posts = Post.objects.order_by('-pub_date')[:10]
    # В словаре context отправляем информацию в шаблон
    context = {
        'title': title,
        'posts': posts,
    }
    return render(request, 'posts/index.html', context) 


# Страница с постами сгруппированными по темам
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group__slug=slug).order_by('-pub_date')[:10]
    # В словаре context отправляем информацию в шаблон
    context = {
        'slug': group.slug,
        'title': group.title,
        'description': group.description,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    {% load static %}
    <link rel="icon" href="{% static img/fav/fav.ico }" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static img/fav/apple-touch-icon.png}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static img/fav/favicon-32x32.png}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static img/fav/favicon-16x16.png}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{{ title }}</title>
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container">
      <h1>{{ title }}</h1>
      {% block content %}
        Content.
      {% endblock %} 
      </div> 
    </main>
      {% include 'includes/footer.html' %} 
  </body>
</html> 

yatube/templates/includes/footer.html
    <footer class="border-top text-center py-3">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
      <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>

yatube/templates/includes/header.html
 <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="index.html">
          {% load static %}
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube</a>
          </a>
        </div>
      </nav>      

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
  <p>{{ description }}</p>
  {% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
  {% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
  <a href="{% url 'posts:group_posts_list' post.group.slug %}">все записи группы</a>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
{% endblock %}